# Generated by Django 5.2.3 on 2025-06-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacionescatacion', '0002_remove_evaluacioncacao_aroma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncacao',
            name='acidez_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='evaluacioncacao',
            name='defectos_totales',
            field=models.FloatField(default=0.0),
        ),
    ]
